name: mal-box
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: master
jobs:
  updateGist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - run: npm install
      - name: "Update gist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          MAL_USERNAME: ${{ secrets.MAL_USERNAME }}
