name: mal-box-anime
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches: master
jobs:
  updateGist:
    runs-on: ubuntu-latest
    environment: anime
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Install"
        run: npm install --save-dev
      - name: "Build"
        run: npm run build
      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          MAL_USERNAME: ${{ secrets.MAL_USERNAME }}
          MAL_MODE: ${{ secrets.MAL_MODE }}
        run: npm run start
        
